name: weather_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.7
  fl_chart: ^0.55.1
  dotted_line: ^3.1.0
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  get_it: ^7.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  internet_connection_checker: ^0.0.1+4
  geolocator: ^9.0.1
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: weather/app_icon.png,
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - weather/
    - weather/64x64/day/
    - weather/64x64/night/
